package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class PacientAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacientAllPropertiesEquals(Pacient expected, Pacient actual) {
        assertPacientAutoGeneratedPropertiesEquals(expected, actual);
        assertPacientAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacientAllUpdatablePropertiesEquals(Pacient expected, Pacient actual) {
        assertPacientUpdatableFieldsEquals(expected, actual);
        assertPacientUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacientAutoGeneratedPropertiesEquals(Pacient expected, Pacient actual) {
        assertThat(actual)
            .as("Verify Pacient auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacientUpdatableFieldsEquals(Pacient expected, Pacient actual) {
        assertThat(actual)
            .as("Verify Pacient relevant properties")
            .satisfies(a -> assertThat(a.getCnp()).as("check cnp").isEqualTo(expected.getCnp()))
            .satisfies(a -> assertThat(a.getTelefon()).as("check telefon").isEqualTo(expected.getTelefon()))
            .satisfies(a -> assertThat(a.getDataNasterii()).as("check dataNasterii").isEqualTo(expected.getDataNasterii()))
            .satisfies(a -> assertThat(a.getAdresa()).as("check adresa").isEqualTo(expected.getAdresa()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertPacientUpdatableRelationshipsEquals(Pacient expected, Pacient actual) {
        // empty method
    }
}
