package com.mycompany.myapp.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class SpecializareAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSpecializareAllPropertiesEquals(Specializare expected, Specializare actual) {
        assertSpecializareAutoGeneratedPropertiesEquals(expected, actual);
        assertSpecializareAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSpecializareAllUpdatablePropertiesEquals(Specializare expected, Specializare actual) {
        assertSpecializareUpdatableFieldsEquals(expected, actual);
        assertSpecializareUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSpecializareAutoGeneratedPropertiesEquals(Specializare expected, Specializare actual) {
        assertThat(actual)
            .as("Verify Specializare auto generated properties")
            .satisfies(a -> assertThat(a.getId()).as("check id").isEqualTo(expected.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSpecializareUpdatableFieldsEquals(Specializare expected, Specializare actual) {
        assertThat(actual)
            .as("Verify Specializare relevant properties")
            .satisfies(a -> assertThat(a.getNume()).as("check nume").isEqualTo(expected.getNume()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertSpecializareUpdatableRelationshipsEquals(Specializare expected, Specializare actual) {
        assertThat(actual)
            .as("Verify Specializare relationships")
            .satisfies(a -> assertThat(a.getMedicis()).as("check medicis").isEqualTo(expected.getMedicis()));
    }
}
